const books = [
  {
    title: 'Learning MongoDB',
    author: 'John Smith',
    genre: 'Database',
    description: 'Beginner friendly MongoDB book for basic CRUD and queries.',
    price: 399,
    pages: 280,
    rating: 4.5,
    published: true,
    featured: true,
    publishedYear: 2022,
    tags: ['mongodb', 'beginner', 'database'],
  },
  {
    title: 'Node.js for Students',
    author: 'Amina Khan',
    genre: 'Programming',
    description: 'Easy Node.js examples for classroom practice.',
    price: 299,
    pages: 220,
    rating: 4.2,
    published: true,
    featured: false,
    publishedYear: 2021,
    tags: ['node', 'javascript', 'backend'],
  },
  {
    title: 'Express in Simple Steps',
    author: 'David Lee',
    genre: 'Programming',
    description: 'Small Express API examples with clear structure.',
    price: 350,
    pages: 240,
    rating: 4.3,
    published: true,
    featured: false,
    publishedYear: 2023,
    tags: ['express', 'api', 'backend'],
  },
  {
    title: 'Database Basics',
    author: 'Sara Ahmed',
    genre: 'Database',
    description: 'Database concepts with simple examples.',
    price: 250,
    pages: 180,
    rating: 4.0,
    published: true,
    featured: false,
    publishedYear: 2020,
    tags: ['database', 'sql', 'mongodb'],
  },
  {
    title: 'Modern JavaScript',
    author: 'John Smith',
    genre: 'JavaScript',
    description: 'A practical guide to modern JavaScript features.',
    price: 450,
    pages: 340,
    rating: 4.7,
    published: true,
    featured: true,
    publishedYear: 2024,
    tags: ['javascript', 'frontend', 'backend'],
  },
  {
    title: 'MongoDB Query Practice',
    author: 'Fatima Noor',
    genre: 'Database',
    description: 'Practice book for filters, sorting, pagination and aggregation.',
    price: 420,
    pages: 300,
    rating: 4.6,
    published: false,
    featured: false,
    publishedYear: 2025,
    tags: ['mongodb', 'queries', 'practice'],
  },
  {
    title: 'API Design for Beginners',
    author: 'Michael Brown',
    genre: 'Programming',
    description: 'How to structure a simple API step by step.',
    price: 375,
    pages: 260,
    rating: 4.1,
    published: true,
    featured: false,
    publishedYear: 2023,
    tags: ['api', 'express', 'node'],
  },
  {
    title: 'Full Stack Starter',
    author: 'Amina Khan',
    genre: 'Web Development',
    description: 'A beginner full stack roadmap with projects.',
    price: 500,
    pages: 360,
    rating: 4.8,
    published: true,
    featured: true,
    publishedYear: 2024,
    tags: ['fullstack', 'mern', 'projects'],
  },
];

export default books;